Install test scripts into chroot.
This also removes support for all scripts that don't really work without a chroot
to only run inside a chroot.  This includes:

run_remote_tests
cros_run_vm_tests
parallel_run_vm_tests

Change-Id: I5c89466047047025de6c934b38ef6be8a23ea058

BUG=chromium-os:13498
TEST=Ran full x86-generic-pre-flight-queue with this CL patched in. CBuildbot / CBuild already have their test calls uses enter_chroot.sh -- before their test call.

Review URL: http://codereview.chromium.org/6736023

diff --git a/cros_run_vm_test b/cros_run_vm_test
--- a/cros_run_vm_test
+++ b/cros_run_vm_test
@@ -6,13 +6,11 @@
 #
 # Runs a given test case under a VM.
 
-. $(dirname "$(readlink -f "$0")")/outside_chroot_common.sh 2> /dev/null ||
-  SCRIPT_ROOT=/usr/lib/crosutils
-. "${SCRIPT_ROOT}/common.sh" ||
-  (echo "Unable to load common.sh" && false) ||
-  exit 1
-. "${SCRIPT_ROOT}/lib/cros_vm_lib.sh" || die "Unable to load cros_vm_lib.sh"
-. "${SCRIPT_ROOT}/lib/cros_vm_constants.sh" || \
+# This can only run inside the chroot.
+CROSUTILS=/usr/lib/crosutils
+. "${CROSUTILS}/common.sh" || exit 1
+. "${CROSUTILS}/lib/cros_vm_lib.sh" || die "Unable to load cros_vm_lib.sh"
+. "${CROSUTILS}/lib/cros_vm_constants.sh" ||
   die "Unable to load cros_vm_constants.sh"
 
 get_default_board
@@ -24,8 +22,6 @@ DEFINE_string results_dir_root "" "alternate root results directory"
 DEFINE_string test_case "" "Name of the test case to run"
 DEFINE_boolean use_emerged ${FLAGS_FALSE} \
     "Force use of emerged autotest packages"
-DEFINE_string verify_chrome_version "" \
-    "Verify that this chrome version matches that on vm."
 
 set -e
 
@@ -40,7 +36,7 @@ FLAGS "$@" || exit 1
 
 # Use latest if not specified.
 if [ -z "${FLAGS_image_path}" ]; then
-  LATEST_IMAGE="$(${SCRIPTS_DIR}/get_latest_image.sh \
+  LATEST_IMAGE="$("${CROSUTILS}/get_latest_image.sh" \
       --board=${FLAGS_board})/${DEFAULT_QEMU_IMAGE}"
   info "Using latest vm image ${LATEST_IMAGE}"
   FLAGS_image_path=${LATEST_IMAGE}
@@ -72,20 +68,7 @@ trap stop_kvm EXIT
 start_kvm "${FLAGS_image_path}"
 retry_until_ssh
 
-if [ -n "${FLAGS_verify_chrome_version}" ]; then
-  info "Verifying version of Chrome matches what we expect."
-  if chrome_version_is_valid "${FLAGS_verify_chrome_version}"; then
-    chrome_version_on_vm=$("${SCRIPTS_DIR}/bin/cros_get_chrome_version" \
-        --remote=127.0.0.1 \
-        --ssh_port=${FLAGS_ssh_port})
-    [[ ${chrome_version_on_vm} == ${FLAGS_verify_chrome_version} ]] || \
-        warn "CHROME_VERSION is no longer set.This check will be removed"
-  else
-    warn "${FLAGS_verify_chrome_version} is not a valid Chrome version"
-  fi
-fi
-
-"${SCRIPTS_DIR}/run_remote_tests.sh" \
+run_remote_tests.sh \
     --board=${FLAGS_board} \
     --ssh_port=${FLAGS_ssh_port} \
     --remote=127.0.0.1 \
